"""add_route_id_to_search_logs

Revision ID: 337d5277bab4
Revises: 3b7a25a849c2
Create Date: 2025-07-17 01:56:16.413929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337d5277bab4'
down_revision: Union[str, Sequence[str], None] = '3b7a25a849c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_logs', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'search_logs', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_logs', type_='foreignkey')
    op.drop_column('search_logs', 'route_id')
    # ### end Alembic commands ###
